/* XPM */
static char * fisharray_xpm[] = {
"532 25 248 2",
"  	c None",
". 	c #546392",
"+ 	c #3B417D",
"@ 	c #002174",
"# 	c #65658D",
"$ 	c #001A6E",
"% 	c #002F7E",
"& 	c #5E6990",
"* 	c #47497F",
"= 	c #002578",
"- 	c #002878",
"; 	c #003A88",
"> 	c #005794",
", 	c #006BA2",
"' 	c #00629A",
") 	c #005298",
"! 	c #00508E",
"~ 	c #005D9E",
"{ 	c #00458C",
"] 	c #004A88",
"^ 	c #00348A",
"/ 	c #485388",
"( 	c #0B7FB5",
"_ 	c #42E6E8",
": 	c #58F2DA",
"< 	c #69F9DC",
"[ 	c #5DEFE3",
"} 	c #35D4E3",
"| 	c #0063A8",
"1 	c #2EC1CE",
"2 	c #67EFD7",
"3 	c #58E4DF",
"4 	c #21A2B9",
"5 	c #004E9E",
"6 	c #4BD9C3",
"7 	c #53F3D3",
"8 	c #41D7CB",
"9 	c #3ECCC7",
"0 	c #00709E",
"a 	c #5CEED1",
"b 	c #59F9D9",
"c 	c #14B1C8",
"d 	c #39C2C7",
"e 	c #015F8F",
"f 	c #11B4C3",
"g 	c #8D898D",
"h 	c #003E78",
"i 	c #54FEE4",
"j 	c #60FEDF",
"k 	c #68FED9",
"l 	c #63FBE3",
"m 	c #006EB4",
"n 	c #00146A",
"o 	c #17497D",
"p 	c #297383",
"q 	c #3EA898",
"r 	c #67EFC4",
"s 	c #004592",
"t 	c #002060",
"u 	c #365C64",
"v 	c #24495A",
"w 	c #94D989",
"x 	c #78F2BA",
"y 	c #29CBC5",
"z 	c #9ED2B4",
"A 	c #8ADE92",
"B 	c #6FF9D3",
"C 	c #00246E",
"D 	c #24C6C8",
"E 	c #0790AD",
"F 	c #00387E",
"G 	c #F0DEAC",
"H 	c #EFE1C5",
"I 	c #D4AE54",
"J 	c #EF9117",
"K 	c #F3A715",
"L 	c #F3AB11",
"M 	c #B9C050",
"N 	c #4AFCEA",
"O 	c #38F2E2",
"P 	c #0589B5",
"Q 	c #575C8B",
"R 	c #EBD29B",
"S 	c #DEC89E",
"T 	c #F5ECD3",
"U 	c #E8B230",
"V 	c #F29F1C",
"W 	c #F3A817",
"X 	c #C1BD4D",
"Y 	c #4AFCF2",
"Z 	c #A5A083",
"` 	c #F8F4E6",
" .	c #DEAB4A",
"..	c #D4B24A",
"+.	c #547792",
"@.	c #F8F7EE",
"#.	c #F5F9F5",
"$.	c #32B9BE",
"%.	c #D2BE38",
"&.	c #E5B81B",
"*.	c #DAB534",
"=.	c #CDB477",
"-.	c #A3D177",
";.	c #CFB96D",
">.	c #EAEBE7",
",.	c #D0D4D0",
"'.	c #4FE3C9",
").	c #DBDDD9",
"!.	c #E6B84A",
"~.	c #E0A934",
"{.	c #F4B520",
"].	c #F2A020",
"^.	c #F09520",
"/.	c #79E1A0",
"(.	c #16C1DA",
"_.	c #73BEC3",
":.	c #EFDBB5",
"<.	c #EBCE8F",
"[.	c #F3B51F",
"}.	c #F3A61F",
"|.	c #B0C76B",
"1.	c #C7C7C1",
"2.	c #C6C6B6",
"3.	c #C9C43D",
"4.	c #79FDD0",
"5.	c #0C82A0",
"6.	c #819295",
"7.	c #4F5620",
"8.	c #8CC0C2",
"9.	c #9BC3C5",
"0.	c #10A0C4",
"a.	c #55F7F5",
"b.	c #F19B1F",
"c.	c #F4AC22",
"d.	c #EDC371",
"e.	c #878397",
"f.	c #33D3CD",
"g.	c #35D7D9",
"h.	c #45EFD9",
"i.	c #CBAB5F",
"j.	c #E9C453",
"k.	c #ECD070",
"l.	c #E8C266",
"m.	c #000000",
"n.	c #E9C881",
"o.	c #F4C73C",
"p.	c #F19B21",
"q.	c #5DFDEC",
"r.	c #44FCE4",
"s.	c #D7BE89",
"t.	c #F1C141",
"u.	c #747773",
"v.	c #475253",
"w.	c #E6B738",
"x.	c #F0CC3C",
"y.	c #928D84",
"z.	c #A49F50",
"A.	c #858363",
"B.	c #686C40",
"C.	c #F0B70C",
"D.	c #8D8A49",
"E.	c #32D6C9",
"F.	c #03A0B3",
"G.	c #F1CB47",
"H.	c #94D474",
"I.	c #F3A317",
"J.	c #EBC233",
"K.	c #917B2D",
"L.	c #85A2B7",
"M.	c #D79B0B",
"N.	c #F2AE0C",
"O.	c #CCC4AA",
"P.	c #B8CAA4",
"Q.	c #F2BE30",
"R.	c #F2C62E",
"S.	c #6DDDA7",
"T.	c #0CB7C2",
"U.	c #1CD0C9",
"V.	c #AAC587",
"W.	c #ADC064",
"X.	c #DDCA4F",
"Y.	c #88EEA3",
"Z.	c #C9B141",
"`.	c #63E5AC",
" +	c #193649",
".+	c #064C74",
"++	c #86915D",
"@+	c #5BB579",
"#+	c #F5CA45",
"$+	c #D9C019",
"%+	c #C0CB63",
"&+	c #F2CC32",
"*+	c #7FF3B0",
"=+	c #717495",
"-+	c #AFD175",
";+	c #F2BD1A",
">+	c #7FC77D",
",+	c #EED382",
"'+	c #6DC387",
")+	c #8BCA64",
"!+	c #88D379",
"~+	c #7ADE92",
"{+	c #E3CA3F",
"]+	c #DFB715",
"^+	c #000050",
"/+	c #8ECA74",
"(+	c #1888A0",
"_+	c #64D8AE",
":+	c #BCC73D",
"<+	c #D1CD53",
"[+	c #9DEA8E",
"}+	c #16BCBE",
"|+	c #002828",
"1+	c #E2C53C",
"2+	c #B8D270",
"3+	c #8EE892",
"4+	c #6C7EA4",
"5+	c #001416",
"6+	c #4CBC93",
"7+	c #AAC575",
"8+	c #A8B64A",
"9+	c #A8E785",
"0+	c #002D78",
"a+	c #57D3C0",
"b+	c #EF901F",
"c+	c #45BFA1",
"d+	c #34B2AA",
"e+	c #73924A",
"f+	c #779C4C",
"g+	c #7DBDC5",
"h+	c #F4C024",
"i+	c #639D68",
"j+	c #3C5244",
"k+	c #538F71",
"l+	c #BCB42E",
"m+	c #577D5C",
"n+	c #D5900B",
"o+	c #B49972",
"p+	c #A95E0D",
"q+	c #C8870A",
"r+	c #B8810A",
"s+	c #8FA458",
"t+	c #3FE3D5",
"u+	c #C2960E",
"v+	c #A29830",
"w+	c #B0AC4C",
"x+	c #5E684A",
"y+	c #134663",
"                          . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                           ",
"                        + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                         ",
"                      # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             & $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ &                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                       ",
"                    * = % % % % = *                                         * = - % % % = *                                         * = % - % % = *                                         * = % % % % = *                                         * = % % - % = *                                         * = % % % - = *                                         * = % % % % = *                                         * - % % % % = *                                         * = % % - % = *                                         * = % % % % = *                                         * = % - % % = *                                         * = % % % % - *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                     ",
"                  & $ ; > , ' ) % $ &                                     & $ % ; ! ~ { % $ &                                     & $ % > ' ' % % $ &                                     & $ % % ] ] % % $ &                                     & $ % % ' ' > % $ &                                     & $ % { ~ ! ; % $ &                                     & $ % ) ' , > ; $ &                                     & $ ; ) ' ' ] % $ &                                     & $ % % { > ; ^ $ &                                     & $ % % { { % % $ &                                     & $ ^ ; > { % % $ &                                     & $ % ] ' ' ) ; $ &                                     & $ ; > , ' ) % $ &                                     & $ ; > , ' ) % $ &                                     & $ ; > , ' ) % $ &                                     & $ ; > , ' ) % $ &                                     & $ ; > , ' ) % $ &                                     & $ ; > , ' ) % $ &                                     & $ ; > , ' ) % $ &                   ",
"                / = ( _ : < < [ } ( = /                                 / = ^ | 1 2 [ 3 4 5 = /                                 / = % ' 6 7 7 8 ] % = /                                 / = % % ! 9 9 ! % % = /                                 / = % ] 8 7 7 6 ' % = /                                 / = 5 4 3 [ 2 1 | ^ = /                                 / = ( } [ < < : _ ( = /                                 / = 0 1 a b b 2 c ; = /                                 / = % % 0 d : 6 e % = /                                 / = % % % f f % % % = /                                 / = % e 6 : d 0 % % = /                                 / = ; c 2 b b a 1 0 = /                                 / = ( _ : < < [ } ( = /                                 / = ( _ : < < [ } ( = /                                 / = ( _ : < < [ } ( = /                                 / = ( _ : < < [ } ( = /                                 / = ( _ : < < [ } ( = /                                 / = ( _ : < < [ } ( = /                                 / = ( _ : < < [ } ( = /                 ",
"              g h 9 < b i j k k k l m n &                             g o p q r 2 l i j < 3 s n &                             & t u v q w w x k y ! % n &                             & n % % u z A A z u % % n &                             & n % ! y k x w w q v u t &                             & n s 3 < j i l 2 r q p o g                             & n m l k k k j i b < 9 h g                             & n ' 9 B k j i l l 1 e C #                             & n % % { D j j < a E o n &                             & n % % F p 8 8 p F % % n &                             & n o E a < j j D { % % n &                             # C e 1 l l i j k B 9 ' n &                             g h 9 < b i j k k k l m n &                             g h 9 < b i j k k k l m n &                             g h 9 < b i j k k k l m n &                             g h 9 < b i j k k k l m n &                             g h 9 < b i j k k k l m n &                             g h 9 < b i j k k k l m n &                             g h 9 < b i j k k k l m n &               ",
"            G H I J K L M x N j k k O P = Q                         R S T T U V W X x Y j k c ^ - Q                         Q - Z ` G  .T T ..k k D ; % = Q                         Q = % % +.@.#.T T #.@.+.% % = Q                         Q = % ; D k k ..T T  .G ` Z - Q                         Q - ^ c k j Y x X W V U T T S R                         Q = P O k k j N x M L K J I H G                         Q = { $.i j Y N r %.&.&.*.=.S Z                         Q { { % > d < k j -.%.;.>.+.= Q                         Q = % % % ,.;.'.'.;.).% % % = Q                         Q = +.>.;.%.-.j k < d > % { { Q                         Z S =.*.&.&.%.r N Y j i $.{ = Q                         !.~.~.J K L M x N j k k O P = Q                         !.~.~.J K L M x N j k k O P = Q                         !.~.~.J K L M x N j k k O P = Q                         !.~.~.J K L M x N j k k O P = Q                         !.~.~.J K L M x N j k k O P = Q                         !.~.~.J K L M x N j k k O P = Q                         !.~.~.J K L M x N j k k O P = Q             ",
"          H #.,.@.~.{.].^.V %./.i k k j (.n #     _._.            :.<.@.,.).:.[.}.^.K |.l i j 4 % n & _._.                # n % :.1.).:.).2.T 3.4.7 5., , n #                     # n % % % 6.,.7.T T 7.,.6.% % % n #                     # n , , 5.7 4.3.T 2.).:.).1.:.% n #                 _._.& n % 4 j i l |.K ^.}.[.:.).,.@.<.:.            _._.    # n (.j k k i /.%.V ^.].{.~.@.,.#.H               8.D 9.# n % 0.a.N Y /.X b.^.b.c.d.@.).2.e.                    # k f.f.; 5.g.j A X V }.T >.>.% n #                     # n % % % 6.` }.h.h.}.` 6.% % % n #                     # n % >.>.T }.V X A j g.5.; f.f.k #                     e.2.).@.d.c.b.^.b.X /.Y N a.0.% n # 9.D 8.              i.....I ~.{.].^.V %./.i k k j (.n #     _._.            ~.j.k.l.~.{.].^.V %./.i k k j (.n #     _._.            j.k.k.k.~.{.].^.V %./.i k k j (.n #     _._.            j.k.k.k.~.{.].^.V %./.i k k j (.n #     _._.            j.k.k.k.~.{.].^.V %./.i k k j (.n #     _._.            ~.j.k.l.~.{.].^.V %./.i k k j (.n #     _._.            i.....I ~.{.].^.V %./.i k k j (.n #     _._.  ",
"        [.@.1.m.>.n.o.o.].].p.V -.q.j j l ) = e Y r.k y         s.t.!.#.u.v.T w.x.}.V ^.%.q.i : ) { P k k y             # = % % T y.z.H A.B.#.C.&./.6 k k 0 = #                 # = % % % % D.#.#.G G #.#.D.% % % % = #                 # = 0 k k 6 /.&.C.#.B.A.H z.y.T % % = #             y k k P { ) : i q.%.^.V }.x.w.T v.u.#.!.t.s.        y k r.Y e = ) l j j q.-.V p.].].o.o.n.>.m.1.@.[.            $.k E.F.{ m g.N Y A V p.b.V [.G.n.).m.).s.#                 # = 8 k i f.D N H.I.b.b.J.i.m.>.K.% = #                 # = % % % % L.n.p.h.h.p.d.L.% % % % = #                 # = % K.>.m.i.J.b.b.I.H.N D f.i k 8 = #                 # s.).m.).n.G.[.V b.p.V A Y N g.m { F.E.k $.            [.@.1.m.>.n.o.o.].].p.V -.q.j j l ) = e Y r.k y         [.` M.M.s.n.o.o.].].p.V -.q.j j l ) = e Y r.k y         N.k.k.k.k.M.o.o.].].p.V -.q.j j l ) = e Y r.k y         [.k.k.k.k.n.o.o.].].p.V -.q.j j l ) = e Y r.k y         N.k.k.k.k.M.o.o.].].p.V -.q.j j l ) = e Y r.k y         [.` M.M.s.n.o.o.].].p.V -.q.j j l ) = e Y r.k y         [.@.1.m.>.n.o.o.].].p.V -.q.j j l ) = e Y r.k y ",
"    O.{.J.:.#.).@.!.x.G.[.b.].].b.%.A b N (.} i k k k y       P.{.Q.t.T #.>.R R.G.Q.b.].^.%.S.: c T.j k k U.          # n % ! 0 V.W.X.l.@.#.:.J.].W N.Y.k 0 % n #             # n % % % % F Z.j.V.V.V.V.j.Z.F % % % % n #             # n % 0 k Y.N.W ].J.:.#.@.l.X.W.V.0 ! % n #           U.k k j T.c : S.%.^.].b.Q.G.R.R >.#.T t.Q.{.P.      y k k k i } (.N b A %.b.].].b.[.G.x.!.@.).#.:.J.{.O.        y < b : g.y N `.%.V p.V b.}.o.G.j.H ).#.!. +#             # n % f j i i S.|.I.V V V {.G.=.T *..+% n #             # n % % % % % ++Q.p././.p.o.++% % % % % n #             # n % .+*.T =.G.{.V V V I.|.S.i i j f % n #             #  +!.#.).H j.G.o.}.b.V p.V %.`.N y g.: b < y         O.{.J.:.#.).@.!.x.G.[.b.].].b.%.A b N (.} i k k k y     O.{.J.:.T G @.!.x.G.[.b.].].b.%.A b N (.} i k k k y     O.{.J.I ....I !.x.G.[.b.].].b.%.A b N (.} i k k k y     O.{.w.d.k.k.k. .x.G.[.b.].].b.%.A b N (.} i k k k y     O.{.J.I ....I !.x.G.[.b.].].b.%.A b N (.} i k k k y     O.{.J.:.T G @.!.x.G.[.b.].].b.%.A b N (.} i k k k y     O.{.J.:.#.).@.!.x.G.[.b.].].b.%.A b N (.} i k k k y ",
"8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.    T.T.%+&+R.w.R <.t.x.G.o.b.p.I.b.b.&.W.*+k k b 8.        =+= % % 0 k k k S.#+l.d.#+#+Q.c.&.-+k 0 % % = =+        =+= % % % % % h *.X.r 4.4.r X.*.h % % % % % = =+        =+= % % 0 k -+&.c.Q.#+#+d.l.#+S.k k k 0 % % = =+        8.b k k *+W.&.b.b.I.p.b.o.G.x.t.<.R w.R.&+%+T.T.    8.7 k k j H.3.$+V ].].].].].p.o.#+x.R.l.H R U x.R.@+T.8.    _.B k N S.;+C.V b.b.I.].V }.G.o.G.#+H R C.>+E =+        =+= % % 0 k i %+].^.V V V V b.G.,+j.G.5.% % = =+        =+= % % % % % % z.o.p.A A p.o.z.% % % % % % = =+        =+= % % 5.G.j.,+G.b.V V V V ^.].%+i k 0 % % = =+        =+E >+C.R H #+G.o.G.}.V ].I.b.b.V C.;+S.N k B _.    8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.8.T.@+R.x.M.l.k.I R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.8.T.@+R.x.U R H l.R.x.#+o.p.].].].].].V $+3.H.j k k 7 8.",
"y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8     $.4.i E.%+R.x.J.R.x.G.o.{+H.A `.]+].b.V /.k k y o         ^+% % % E.k E.E.7 S.j.w.%.%+w /+K %+k 5.% % % ^+        ^+% % % % 5.(+5.%._+'.E.E.'._+%.5.(+5.% % % % ^+        ^+% % % 5.k %+K /+w %+%.w.j.S.7 E.E.k E.% % % ^+        o y k k /.V b.].]+`.A H.{+o.G.x.R.J.x.R.%+E.i 4.$.    8 k k j H.^.b.].].W `.~+!+)+X.o.#+x.&+J.R.x.x.'+O 4.y       f.k j x K V V V b.W !+S.A X.x.o.x.J.x.-.B '.C         ^+% % % % f.j A ].].V V V I.%.x A G.A 6 % % % ^+        ^+% % % % % 9 9 >+o.].A A ].o.>+$.9 % % % % % ^+        ^+% % % 6 A G.A x %.I.V V V ].].A j f.% % % % ^+        C '.B -.x.J.x.o.x.X.A S.!+W b.V V V K x j k f.      y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   y 4.O '+x.x.&.&.J.x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   y 4.O '+x.x.R.J.&+x.#+o.X.)+!+~+`.W ].].b.^.H.j k k 8   ",
"8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.        T.h.i T.<+o.G.G.G.o.R.[+q.a.~+V ].b.L r k E.= =+        =+= % % E.k m.m.m.}+_+G.x k k : L %+8 % % % = =+        =+= % % % 4.4.x X.B |+m.m.|+B 1+x 4.4.% % % = =+        =+= % % % 8 %+L : k k x G._+}+m.m.m.k E.% % = =+        =+= E.k r L b.].V ~+a.q.[+R.o.G.G.G.o.<+T.i h.T.        U.k j k I.].].].b.:+i l l *+x.o.#+#+#+o.o.'+Y j T.8.        f.k B C.V ].p.b.I.%.q.Y Y.x.#+o.o.-.4.8 = =+        =+= % % % T.k Y &.].].b.b.I.M.k Y <+4.0 % % = =+        =+= % % % % 8 k [+o.].A A ].o.[+k 8 % % % % = =+        =+= % % 0 4.<+Y k M.I.b.b.].].&.Y k T.% % % = =+        =+= 8 4.-.o.o.#+x.Y.Y q.%.I.b.p.].V C.B k f.        8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    8.T.j Y '+o.o.#+#+#+o.x.*+l l i :+b.].].].I.k j k U.    ",
"      f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          4+5.N _+{+o.G.o.o.2+i < w I.b.b.V |.k k E.#             # n % ! E.5+m.m.5+6+X.r 7 7 /+C.|.y - % n #             # n % % f 4.x 7+F.m.m.m.m.F.7+x 4.f % % n #             # n % - y |.C./+7 7 r X.6+5+m.m.5+E.! % n #             # E.k k |.V b.b.I.w < i 2+o.o.G.o.{+_+N 5.4+          U.k k q.X b.].].V V 3.r r.i 3+x.#+#+#+o.2+O f.              f.k j A C.V ].b.V b.8+N q.9+#+o.o.[+y 0+#             # n % % T.k B |.].V b.b.V M.w Y X.a+% % n #             # n % % % (+4 u Q.p.A A p.Q.u 4 (+% % % n #             # n % % a+X.Y w M.V b.b.V ].|.B k T.% % n #             # 0+y [+o.o.#+9+q.N 8+b.V b.].V C.A j k f.              f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.          f.O 2+o.#+#+#+x.3+i r.r 3.V V ].].b.X q.k k U.    ",
"    T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.            T.b N 2+o.G.G.G.X.C.L b+].].V &.B k k E.                # = % % T.6 6 T.c+#+G.A /.].|.k T.% = #                 # = % % 5.c+7+B '.6 6 '.4.7+c+5.% % = #                 # = % T.k |.]./.A G.#+c+T.6 6 T.% % = #                 E.k k B &.V ].].b+L C.X.G.G.G.o.2+N b T.            U.k k j r W b.p.p.p.p.V L N.1+x.#+#+#+o.Y.j T.T.            f.k k Y w I.p.p.].].V K L {.o.o.o.Y.4.d+                # = % T.k B /.}.].p.V V V c.Q.2+4.5.= #                 # = % % % % % {.p.A A p.{.% % % % % = #                 # = 5.4.2+Q.c.V V V p.].}./.B k T.% = #                 d+4.Y.o.o.o.{.L K V ].].p.p.I.w Y k k f.            T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.        T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.        T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.        T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.        T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.        T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.        T.T.j Y.o.#+#+#+x.1+N.L V p.p.p.p.b.W r j k k U.    ",
"  8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.          g+U.U.6 X.&+&+&+h+].].&.|.i+j+k+6+i k k D                   # n % q a a '+X.Q.[.K L -+4.h., n #                     # n % % F z.|.'.a a '.|.z.F % % n #                     # n , h.4.-+L K [.Q.X.'+a a q % n #                   D k k i 6+k+j+i+|.&.].].h+&+&+&+X.6 U.U.g+          U.k k k j r -.)+f+e+W.%.K ^.].{.R.&+&+R.2+'.E.E.8.          f.k k k B H.M l+X X w *.V I.L ;+Q.-.E._.                  # n T.k B N H.X %.%.7+N.K C.m+0 @ #                     # n % % % % n+K A A K n+% % % % n #                     # @ 0 m+C.K N.7+%.%.X H.N B k T.n #                   _.E.-.Q.;+L I.V *.w X X l+M H.B k k k f.          8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.      8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.      8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.      8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.      8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.      8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.      8.E.E.'.2+R.&+&+R.{.].^.K %.W.e+f+)+-.r j k k k U.    ",
"            o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 6.j+q+M.u+r+D._+_ } | % % | t+t+t+g+                    Q = .+v+v+u+V n+q+8+7 5.F.F.- Q                         Q = % % % w+*.U U *.w+% % % = Q                         Q - F.F.5.7 8+q+n+V u+v+v+.+= Q                     g+t+t+t+| % % | } _ _+D.r+u+M.q+j+6.                D 7 b b t+f | ^ % s } a.a./.s+r+q+q+p+o+                    y : : '.T.F.5 m 1 ( _ a.D v+K.B.x+y.                        Q F.B B a 2 d 0.0.a.8 B.F % = Q                         Q = % % % h S.~+~+S.h % % % = Q                         Q = % F B.8 a.0.0.d 2 a B B F.Q                         y.x+B.K.v+D a._ ( 1 m 5 F.T.'.: : y                     o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D                 o+p+q+q+r+s+/.a.a.} s % ^ | f t+b b 7 D     ",
"              & n % % % 5 | ~ s % % % n & 9.9.9.9.                    # C % 0+% ^ ^ 5 s % % % n &                             & n % v j+j+y+> > > ; % n &                             & n % % ! e v v.e ! % % n &                             & n % ; > > > y+j+j+v % n &                             & n % % % s 5 ^ ^ % 0+% C #                     9.9.9.9.& n % % % s ~ | 5 % % % n &                         g+g+g+F % % % { ; > ~ ; % % n &                             & (+D > % { % ) ' ) % % n &                             & n % % F 0 }+}+0 F % % n &                             & n % % ) ' ) % { % > D (+&                             & n % % ; ~ > ; { % % % F g+g+g+                        & n % % % 5 | ~ s % % % n & 9.9.9.9.                    & n % % % 5 | ~ s % % % n & 9.9.9.9.                    & n % % % 5 | ~ s % % % n & 9.9.9.9.                    & n % % % 5 | ~ s % % % n & 9.9.9.9.                    & n % % % 5 | ~ s % % % n & 9.9.9.9.                    & n % % % 5 | ~ s % % % n & 9.9.9.9.                    & n % % % 5 | ~ s % % % n & 9.9.9.9.      ",
"                / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % ] ] % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                                 / = % % % % % % % % = /                 ",
"                  & $ % % % % % % $ &                                     & n % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % n &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                                     & $ % % % % % % $ &                   ",
"                    * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                                         * = % % % % = *                     ",
"                      # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                                             # $ % % $ #                       ",
"                        + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                                                 + @ @ +                         ",
"                          . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                                                     . .                           "};
