extern int levelstate_write();
extern int levelstate_read();
extern long levelstate_total_hiscore();
extern long levelstate_get_hiscore();
extern int levelstate_in_progress();
extern int levelstate_next();
extern int levelstate_prev();
extern int get_level_num();
extern char *get_level_desc();
extern void levelstate_finish();
extern void levelstate_go();
extern void levelstate_resume();
extern void levelstate_reset();
extern cairo_surface_t* levelstate_get_icon(int num);
