#!/bin/sh

base=`dirname $0`
chmod 755 $base/ffmpeg2theora-0.21.linux32
$base/ffmpeg2theora-0.21.linux32 $@ > /tmp/testit 2>&1

#echo $@ > /tmp/test1
#echo $1 > /tmp/test2
#echo $2 > /tmp/test3
#echo $3 > /tmp/test4
